galaxy_info:
  author: Mykhaylo Kolesnik
  description: Simply installs MySQL 5.7 on Xenial.
  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: Ubuntu
      versions:
      - xenial
  galaxy_tags:
    - system
    - mysql
